version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "sort-keys"
    commit-message:
      prefix: "Update dependencies"
    pull-request-branch-name:
      separator: "-"
    groups:
      all-dependencies:
        patterns:
          - "*"